# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelHackApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelHackApp

  pod 'Shuffle-iOS'

  target 'TravelHackAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelHackAppUITests' do
    # Pods for testing
  end

end
